- name: install nginix
  hosts: 54.88.23.70
  become: yes #take sudo access
  tasks:
  - name: task 1 to install niginix
    ansible.builtin.package: #hetrongenous module thst csn work for all distributions
      name: nginx
      state: present
  - name: to start run the service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
      

