- name:
  hosts: web
  vars_prompt: #to get variables from the prompt
  - name: course
    prompt: please enter the couse name
    private: false #if it is not a confidential
  - name: trainer
    prompt: please enter the trainer name
  - name: duration
    prompt: please enter the duaration


  tasks: #giving variables from the prompt
  - name: 
    ansible.builtin.debug: 
      msg: "Hi i am learning {{course}},duration is {{duration}} ,Trainer is {{trainer}}"