- name:
  hosts: web
  vars_prompt:
  - name: course
    prompt: please enter the couse name
  - name: tariner
    prompt: please enter the trainer name
  - name: duartion

  tasks: #giving variables from the prompt
  - name: 
    ansible.builtin.debug: 
      msg: "Hi i am learning {{course}},duration is {{duration}} ,Trainer is {{trainer}}"