- name:
  hosts: web
  vars_prompt:
  - name: course
    prompt: please enter the couse name
    private: false #not confidential
  - name: trainer
    prompt: please enter the trainer name
  - name: duration

  tasks: #giving variables from the prompt
  - name: 
    ansible.builtin.debug: 
      msg: "Hi i am learning {{course}},duration is {{duration}} ,Trainer is {{trainer}}"