- name: to get the vars from the arguments
  hosts: web
  tasks: 
  - name: vars from args
    ansible.builtin.debug:
      msg: "hello{{name}}very{{greeting}}"


#top level to take from the variables


#from args
