- name: print number is grater then 10n or not
  hosts: local
  connection: local
  vars_prompt: 
  - name: number
    prompt: please enter the number
    private: false
  tasks: 
  - name: 
    ansible.builtin.debug: 
    when: {{numer}} > 10
      msg: "number is {{number}}"
