- name: print number is grater then 10n or not
  hosts: local
  connection: local
  vars_prompt: 
  - name: number
    prompt: please enter the number
    private: false
  tasks: 
  - name: 
    ansible.builtin.debug: 
      msg: "  {{number}} grtaer then 10"
    when:  number | int > 10

  - name: print if the number lessthen 10
    ansible.builtin.debug: 
      msg: "  {{number}} smaller  then 10"
    when:  number | int < 10
    
    
