- name: Tocheck the user exist or not if not to create
  hosts: web
  become: yes
  tasks: 
  - name:
    ansible.builtin.command: id expence
    register: user #user is the variable to store the outout from the above command
    ignore_errors: true
  
  - name: print the user information
    ansible.builtin.debug:
      msg: "user info is {{user}}"
      