- name: Demo on filters/functions
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug: 
      msg: "Hello {{ course | default ('ansible') }}"

  - name: print the upper case
    vars:
      greetings: " Hello masteru "
    ansible.builtin.debug:
      msg: "Hello{{ greetings | upper }}"

  - name: printn the lower case
    vars:
      greetings: " Hello masteru "
    ansible.builtin.debug:
      msg: "Hello{{ greetings | lower }}"

      
  - name: get the unique numbers in the list
    vars:
      numbers: [ 1,4,5,6,4,45,6,5 ]
    ansible.builtin.debug:
      msg: "Hello{{ numbers | unique }}"

  - name: convert dist to items
    vars: 
      course:
        name: aws with devops
        duration: 120 hrs
        trainer: siva
    ansible.builtin.debug:
      msg: "dist to items {{ course | dict2items }}"

  - name: convert list to map
    vars: 
      course:
        - { key: name , value: aws with aws }
        - { key: duration , value: 10 hrs }
        - { key:  trainer , value: siva }
    ansible.builtin.debug:
      msg: "list to map {{ course | items2dict}}"