- name: command vs shell
  hosts: local
  connection: local
  tasks: 
    - name: 
      ansible.builtin.command: ls -ltr > /tmp/output.txt

    - name: 
      ansible.builtin.shell: ls -ltr > /tmp/output.txt
# shell module login within servers and excutes  
# shell module login within servers and excutes
# but incase of command module ,just issues the command 
  