- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars: 
    instance:
    - mysql
    - frontend
    - backend
  tasks:  
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: subnet-015bec7112d00f8ab
      instance_type: "t3.micro"
      security_group: sg-081d20b1a8d4b83e7
      image_id: ami-09c813fb71547fc4f
    loop: "{{ instance }}"
    register: ec2_instances

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"

  # - name: create r53 private records
  #   amazon.aws.route53:
  #     state: present
  #     zone: "{{ zone }}"
  #     record: "{{ item.item}}.{{ zone }}" #mysql.amarvarma81s.online
  #     type: A 
  #     ttl: 1
  #     value: "{{ item.instances[0].private_ip_address }}"
  #     wait: true
  #   loop: "{{ ec2_instances.results }}"

  # - name: create r53 public records
  #   amazon.aws.route53:
  #     state: present
  #     zone: "{{ zone }}"
  #     record: "{{ zone }}" #amarvarma81s.online
  #     type: A 
  #     ttl: 1
  #     value: "{{ item.instances[0].public_ip_address }}"
  #     wait: true
  #   loop: "{{ ec2_instances.results }}"
  #   when: item.item == "frontend"  


      