- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars: 
    zone: amarvarma81s.online

  tasks:
  - name: ansible to install boto3 and botocore
    ansible.builtin.pip:
      name:
      - boto3
      - botocore
      excutable: pip3.9
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: subnet-0cd62018757985576
      instance_type: "t3.micro"
      security_group: sg-0e3d08fb6363e4102
      image_id: ami-09c813fb71547fc4f
    loop: 
      - mysql
      - backend
      - frontend
    register: ec2_instances

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"

  - name: create r53 private records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item}}.{{ zone }}" #mysql.amarvarma81s.online
      type: A 
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
    loop: "{{ ec2_instances.results }}"

  - name: create r53 public records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}" #amarvarma81s.online
      type: A 
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
    loop: "{{ ec2_instances.results }}"
    when: item.item == "frontend"  


      