- name: create ec2 and r53 records
  hosts: local
  connection: local
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      vpc_subnet_id: subnet-015bec7112d00f8ab
      instance_type: "t3.micro"
      security_group: sg-0e3d08fb6363e4102
      image_id: ami-09c813fb71547fc4f
      loop: 
      - { name: 'mysql'}
      - { name: 'backend' }
      - { name: 'frontend' }
       